export function stripAiWarning(text) {
  if (!text) return ''
  return text
    .replace(/^⚠️\s*AI(?:\s*DRAFT|\s*HOLISTIC ANALYSIS)\s*-+[^\n]*\r?\n?/i, '')
    .replace(/\n?⚠️\s*This result was generated by AI[^\n]*/i, '')
    .trim()
}

export function normalizeAiDraftForDisplay(text) {
  if (!text) return ''
  return stripAiWarning(text)
    .replace(/\r\n/g, '\n')
    .replace(/\s*\*\*(\d+\.\s+[^*]+)\*\*\s*/g, '\n\n### $1\n')
    .replace(/\s+\*\s+(?=\*\*|[A-Z0-9])/g, '\n- ')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function stripMarkdown(text) {
  return String(text || '')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^\s*[-*]\s+/gm, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/\s+/g, ' ')
    .trim()
}

export function aiDraftPreview(text, maxLength = 220) {
  const normalized = normalizeAiDraftForDisplay(text)
  if (!normalized) return ''

  const summaryMatch = normalized.match(/###\s*1\.\s+Key Findings Summary\s*([\s\S]*?)(?=\n\n###\s*2\.|$)/i)
  const source = summaryMatch?.[1] || normalized
  const bullets = source
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => /^[-*]\s+/.test(line))
    .slice(0, 2)
    .map(stripMarkdown)

  const preview = bullets.length > 0 ? bullets.join(' ') : stripMarkdown(source)
  if (preview.length <= maxLength) return preview
  return `${preview.slice(0, maxLength).trimEnd()}...`
}

export function parseAiDraft(aiDraftText) {
  if (!aiDraftText) return ''
  const trimmed = aiDraftText.trim()
  if (!trimmed.startsWith('[')) return stripAiWarning(aiDraftText)
  let findings
  try {
    findings = JSON.parse(trimmed)
    if (!Array.isArray(findings) || findings.length === 0) return stripAiWarning(aiDraftText)
  } catch {
    return stripAiWarning(aiDraftText)
  }
  const abnormal = findings.filter((f) => f.flag && f.flag !== 'normal')
  const normal = findings.filter((f) => !f.flag || f.flag === 'normal')
  const lines = []
  if (abnormal.length > 0) lines.push(...buildAbnormalSection(abnormal, findings))
  if (normal.length > 0) lines.push(...buildNormalSection(normal))
  lines.push(...buildClinicalImpression(abnormal, findings))
  return lines.join('\n')
}

// Internal helpers for parseAiDraft
function buildAbnormalSection(abnormal) {
  const lines = ['**1. AI Priority Alerts**']
  for (const f of abnormal) {
    lines.push(`* **${f.name}:** ${f.value} ${f.unit || ''} (Ref: ${f.referenceRange || f.reference_range || '-'})`)
    if (f.clinical_significance) lines.push(`  *Significance:* ${f.clinical_significance}`)
  }
  return lines
}

function buildNormalSection(normal) {
  const lines = ['\n**2. Normal Findings**']
  const names = normal.map((f) => f.name).join(', ')
  lines.push(`* Within normal limits: ${names}`)
  return lines
}

function buildClinicalImpression(abnormal) {
  if (abnormal.length === 0) {
    return ['\n**3. Clinical Impression**', '* Overall results are within normal limits.']
  }
  return ['\n**3. Clinical Impression**', '* Abnormalities require clinical correlation.']
}

export function detectPriority(text) {
  if (!text) return null
  const m = text.match(/priority(?:\s*level)?[:\s*_]*([^\n*]+)/i)
  if (!m) return null
  const v = m[1].toLowerCase().replace(/[*_]/g, '').trim()
  if (v.includes('routine') || v.includes('low')) return 'low'
  if (v.includes('urgent') || v.includes('critical') || v.includes('emergent')) return 'urgent'
  if (v.includes('high')) return 'high'
  if (v.includes('priority')) return 'priority'
  if (v.includes('moderate') || v.includes('medium')) return 'moderate'
  return null
}

export function normalizeStatus(s) {
  if (!s) return 'needs_upload'
  const raw = String(s || '').toUpperCase().trim()
  if (['PUBLISHED', 'REVIEWED', 'VERIFIED', 'COMPLETE', 'COMPLETED'].includes(raw)) return 'published'
  if (['AI_DRAFT', 'DRAFT', 'DOCTOR_REVIEW', 'NEEDS_MANUAL_REVIEW', 'READY_TO_VERIFY', 'READY', 'AI_COMPLETE'].includes(raw)) return 'ready_to_verify'
  if (['PENDING', 'AI_PROCESSING', 'PROCESSING', 'QUEUED', 'UPLOADED'].includes(raw)) return 'processing'
  return 'processing'
}

export function patientLabel(order) {
  return order?.patient_name || order?.patientName || 'Unknown Patient'
}

export function testLabel(order) {
  if (Array.isArray(order?.tests) && order.tests.length > 0) return order.tests.join(', ')
  return order?.test_name || order?.test || 'Lab Test'
}

export function formatDateLabel(value) {
  if (!value) return '—'
  const date = value instanceof Date ? value : new Date(value)
  if (Number.isNaN(date.getTime())) return String(value)
  return date.toLocaleString('en-GB', {
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit',
  })
}
