import PropTypes from 'prop-types'
import { IconArrowLeft, IconSparkle } from '../../icons'

const DEFAULT_LAB = {
  id: 1,
  name: 'Full Blood Panel',
  status: 'New',
  doctor: 'Dr. Sarah Chen',
  date: 'Received Mar 10, 2025',
  explanation:
    "Your results look mostly healthy. Your red blood cell count and white blood cell count are both within expected ranges, which is a good sign. However, your hemoglobin level came in slightly below the normal threshold. This can sometimes cause mild fatigue or low energy. It's not an emergency, but it's worth mentioning to Dr. Chen at your next visit - she may recommend dietary adjustments or a simple iron supplement.",
  details: [
    { test: 'Hemoglobin', yourValue: '11.2 g/dL', normalRange: '12.0-16.0 g/dL', status: 'Low' },
    { test: 'White Blood Cells', yourValue: '6.8 K/uL', normalRange: '4.5-11.0 K/uL', status: 'Normal' },
    { test: 'Platelets', yourValue: '245 K/uL', normalRange: '150-400 K/uL', status: 'Normal' },
    { test: 'Hematocrit', yourValue: '34.1%', normalRange: '36-46%', status: 'Low' },
    { test: 'Red Blood Cells', yourValue: '4.1 M/uL', normalRange: '4.2-5.4 M/uL', status: 'Normal' },
  ],
}

function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  )
}

function statusClass(status) {
  if (status === 'Critical') return 'rounded-lg border border-rose-200 bg-rose-50 px-2 py-0.5 text-rose-600 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-300'
  if (status === 'Low' || status === 'High') return 'rounded-lg border border-amber-200 bg-amber-50 px-2 py-0.5 text-amber-600 dark:border-amber-900/50 dark:bg-amber-950/40 dark:text-amber-300'
  return 'text-slate-400 dark:text-[#606070]'
}

function statusLabel(status) {
  if (status === 'Low') return 'Low'
  if (status === 'High') return 'High'
  if (status === 'Critical') return 'Critical'
  return 'Normal'
}

export default function LabResultDetailView({ setCurrentView, selectedLab }) {
  const lab = selectedLab || DEFAULT_LAB
  const isNew = lab.status === 'New'

  return (
    <div className="mx-auto max-w-4xl">
      <button type="button" className="inline-flex items-center gap-1.5 text-sm text-slate-600 hover:text-slate-900 dark:text-[#9898b0] dark:hover:text-[#eeeef5]" onClick={() => setCurrentView('lab-results')}>
        <IconArrowLeft size={15} />
        Back to Lab Results
      </button>

      <h1 className="mt-4 text-[28px] font-bold leading-tight tracking-tight text-slate-900 dark:text-[#eeeef5]">{lab.name}</h1>
      <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-400 dark:text-[#606070]">
        <span>Ordered by {lab.doctor}</span>
        <span>·</span>
        <span>{lab.date}</span>
        <span>·</span>
        <span className={`rounded-lg border px-2 py-0.5 text-[11px] font-semibold ${isNew ? 'border-indigo-200 bg-indigo-50 text-indigo-700 dark:border-indigo-800/50 dark:bg-indigo-950/60 dark:text-indigo-300' : 'border-slate-200 bg-slate-100 text-slate-500 dark:border-[#252530] dark:bg-[#1c1c25] dark:text-[#70708a]'}`}>{lab.status}</span>
      </div>

      <section className="mt-8 rounded-2xl border border-indigo-100 bg-indigo-50/70 p-5 shadow-[0_8px_32px_rgba(0,0,0,0.06)] backdrop-blur-xl dark:border-indigo-900/40 dark:bg-indigo-950/40 dark:shadow-[0_8px_32px_rgba(0,0,0,0.4)]" aria-labelledby="lrd-ai-heading">
        <div className="mb-3 flex items-center gap-2">
          <span className="text-indigo-600 dark:text-indigo-400"><IconSparkle size={14} /></span>
          <h2 id="lrd-ai-heading" className="text-sm font-semibold tracking-tight text-slate-900 dark:text-[#eeeef5]">AI Plain-Language Summary</h2>
          <span className="ml-auto rounded-lg border border-indigo-200 bg-indigo-100 px-2 py-0.5 text-[11px] font-semibold text-indigo-600 dark:border-indigo-800/50 dark:bg-indigo-950/70 dark:text-indigo-400">Beta</span>
        </div>

        <p className="text-sm leading-relaxed text-slate-600 dark:text-[#9898b0]">{lab.explanation}</p>

        <p className="mt-4 border-t border-indigo-100 pt-4 text-xs text-indigo-400/70 dark:border-indigo-900/40 dark:text-indigo-500/60">
          This summary is generated by AI for informational purposes only and does not constitute medical advice.
        </p>
      </section>

      <section className="mt-8" aria-labelledby="lrd-details-label">
        <p id="lrd-details-label" className="mb-3 text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-400 dark:text-[#505060]">Detailed Results</p>

        <div className="overflow-hidden rounded-2xl border border-slate-200 dark:border-[#252530]">
          <table className="min-w-full border-collapse">
            <thead className="bg-slate-50 dark:bg-[#16161e]">
              <tr className="border-b border-slate-200 dark:border-[#252530]">
                <th className="px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-400 dark:text-[#505060]">Test</th>
                <th className="px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-400 dark:text-[#505060]">Your Value</th>
                <th className="px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-400 dark:text-[#505060]">Normal Range</th>
                <th className="px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-[0.06em] text-slate-400 dark:text-[#505060]">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-[#1c1c25]">
              {lab.details.map((row) => (
                <tr key={row.test} className="bg-white hover:bg-slate-50 dark:bg-[#111118] dark:hover:bg-[#16161e]">
                  <td className="px-4 py-4 text-sm text-slate-600 dark:text-[#9898b0]">{row.test}</td>
                  <td className="px-4 py-4 text-sm text-slate-600 dark:text-[#9898b0]">{row.yourValue}</td>
                  <td className="px-4 py-4 text-sm text-slate-600 dark:text-[#9898b0]">{row.normalRange}</td>
                  <td className="px-4 py-4 text-sm"><span className={statusClass(row.status)}>{statusLabel(row.status)}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <div className="mt-8 flex flex-wrap gap-3">
        <button type="button" className="rounded-xl border border-slate-200 bg-transparent px-4 py-2.5 text-sm font-medium text-slate-600 transition-all duration-150 hover:bg-slate-50 hover:text-slate-900 active:scale-[0.97] dark:border-[#252530] dark:text-[#9898b0] dark:hover:bg-[#16161e] dark:hover:text-[#eeeef5]">
          <span className="inline-flex items-center gap-2"><DownloadIcon />Download PDF</span>
        </button>

        <button type="button" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white transition-all duration-150 hover:-translate-y-px hover:bg-indigo-700 hover:shadow-[0_4px_12px_rgba(99,102,241,0.4)] active:scale-[0.97] dark:bg-indigo-600 dark:hover:bg-indigo-500 dark:hover:shadow-[0_4px_16px_rgba(99,102,241,0.3)]" onClick={() => setCurrentView('symptom-checker')}>
          <span className="inline-flex items-center gap-2"><IconSparkle size={12} />Discuss with AI →</span>
        </button>
      </div>
    </div>
  )
}

LabResultDetailView.propTypes = {
  setCurrentView: PropTypes.func.isRequired,
  selectedLab: PropTypes.shape({
    id: PropTypes.number,
    name: PropTypes.string,
    status: PropTypes.string,
    doctor: PropTypes.string,
    date: PropTypes.string,
    explanation: PropTypes.string,
    details: PropTypes.arrayOf(PropTypes.shape({
      test: PropTypes.string,
      yourValue: PropTypes.string,
      normalRange: PropTypes.string,
      status: PropTypes.string,
    })),
  }),
}
